# Live model
model: pycc/comfyui-live

# A private model to run the test against before pushing
test_model: pycc/comfyui-test2
test_hardware: gpu-l40s

# Tests
predict:
  compare_outputs: false
  predict_timeout: 600
  test_cases:
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/sd15_txt2img.json
        return_temp_files: true

